#!/usr/bin/env python3
"""ledger.py -- the generated inventory behind the coverage ledger, written out to be read.

    python tools/ledger.py CH32L103            # print the inventory (pin functions, chapters, instances)
    python tools/ledger.py --write             # write data/coverage/ledger/<PART>.yaml for every part
    python tools/ledger.py --check             # exit 1 if any written inventory is stale

The inventory is what `tools/coverage.py` reads out of the sources on every run - the
written copy exists so a human or an agent can open `data/coverage/ledger/<PART>.yaml`,
find a row, and follow its `line:` to the datasheet without re-parsing anything. It is
GENERATED and never hand-edited: a wrong row is fixed in the coverage file's
`corrections:` / `pin_aliases:` / `noise:`, or in the parser, and then regenerated.

`--check` is run by tests/coverage.test.js, so a parser change or a datasheet revision
that changes the inventory shows up as a diff of this file rather than silently.

Output is ASCII only: the Windows console here is cp1252.
"""
from __future__ import annotations

import argparse
import sys

import coverage_lib as C

HEADER = ("# GENERATED by tools/ledger.py from the sources named in data/coverage/{part}.yaml.\n"
          "# Do not edit: fix the coverage file or the parser and run `python tools/ledger.py --write`.\n"
          "# Each row's `line:` is the 1-based line in the datasheet markdown it was read from.\n")


def render(res: C.Result) -> str:
    inv = res.inventory
    out = [HEADER.format(part=res.part), f"part: {res.part}", "pin_functions:"]
    for r in inv["pin_functions"]:
        idx = "" if r["index"] is None else f", index: {r['index']}"
        af = "" if r["af"] is None else f", af: {r['af']}"
        out.append(f"  - {{ pin: {r['pin']}, token: {r['token']}{idx}{af}, line: {r['line']} }}")
    out.append("signal_first:")
    for pin, toks in inv["signal_first"].items():
        out.append(f"  {pin}: [{', '.join(toks)}]")
    out.append("chapters:")
    for c in inv["chapters"]:
        title = c["title"].replace('"', "'")
        out.append(f"  - {{ n: {c['n']}, title: \"{title}\", line: {c['line']} }}")
    out.append("instances:")
    for i in inv["instances"]:
        out.append(f"  - {{ name: {i['name']}, typedef: {i['typedef']}, line: {i['line']} }}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="print or write the generated coverage inventory")
    ap.add_argument("parts", nargs="*")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    parts = a.parts or C.real_parts()
    rc = 0
    C.LEDGER_DIR.mkdir(parents=True, exist_ok=True)
    for part in parts:
        try:
            res = C.build(part)
        except C.CoverageError as e:
            print(C.safe(f"ledger: {part}: CANNOT READ - {e}"))
            rc = 2
            continue
        text = render(res)
        target = C.LEDGER_DIR / f"{part}.yaml"
        if a.write:
            target.write_text(text, encoding="utf-8", newline="\n")
            print(f"  wrote {target.relative_to(C.ROOT).as_posix()} ({len(res.inventory['pin_functions'])} pin functions)")
        elif a.check:
            current = target.read_text(encoding="utf-8") if target.is_file() else None
            if current != text:
                print(f"  STALE {target.relative_to(C.ROOT).as_posix()} - run: python tools/ledger.py --write")
                rc = rc or 1
            else:
                print(f"  ok    {target.relative_to(C.ROOT).as_posix()}")
        else:
            sys.stdout.write(C.safe(text))
    return rc


if __name__ == "__main__":
    sys.exit(main())
