// tools/wchcube_cli.js — the engine without a browser.
//
// CI diffs this output, so the contract is: the CLI must produce the same bytes the
// GENERATE CODE button produces, and its exit codes must mean something. If the two
// ever drift, a generated-output diff in CI stops being evidence about the app.
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { test, assert, fresh, eng, ROOT } from './_harness.js';

const CLI = path.join(ROOT, 'tools', 'wchcube_cli.js');

function run(args, opts) {
  const r = spawnSync(process.execPath, [CLI, ...args], {
    cwd: ROOT, encoding: 'utf8', timeout: 60000, ...(opts || {}),
  });
  if (r.error) throw r.error;
  return { code: r.status, out: r.stdout, err: r.stderr };
}

test('--list names every MCU file with its packages', () => {
  const r = run(['--list']);
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /CH32V006/);
  assert.match(r.out, /TSSOP20/);
  // a part that only exists through mcu.inherits must show its inherited packages
  assert.match(r.out, /CH32V005[\s\S]*packages\s+.*TSSOP20/);
});

test('the pin table is byte-identical to the one the app exports', () => {
  const e = fresh('CH32V006', 'TSSOP20');
  const inProcess = e.pinTableMarkdown();
  const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'pins-md', '--quiet']);
  assert.equal(r.code, 0, r.err);
  assert.equal(r.out, inProcess.endsWith('\n') ? inProcess : inProcess + '\n',
    'CLI output drifted from pinTableMarkdown() — CI diffs would stop meaning anything');
});

test('the CSV and the clock summary come out of the same functions', () => {
  const e = fresh('CH32V006', 'QFN32');
  const csv = run(['CH32V006', '--package', 'QFN32', '--format', 'pins-csv', '--quiet']);
  const clk = run(['CH32V006', '--package', 'QFN32', '--format', 'clocks-md', '--quiet']);
  assert.equal(csv.code, 0, csv.err);
  assert.equal(clk.code, 0, clk.err);
  assert.equal(csv.out.trimEnd(), e.pinTableCsv().trimEnd());
  assert.equal(clk.out.trimEnd(), e.clockSummaryMarkdown().trimEnd());
});

test('--format c writes the two init files, --out puts them on disk', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-cli-'));
  try {
    const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'c', '--out', dir, '--quiet']);
    assert.equal(r.code, 0, r.err);
    const written = fs.readdirSync(dir).sort();
    assert.deepEqual(written, ['wchcube_init.c', 'wchcube_init.h']);
    const c = fs.readFileSync(path.join(dir, 'wchcube_init.c'), 'utf8');
    assert.match(c, /generated by WCHCube/);
    assert.match(c, /void WCHCube_GPIO_Init\(void\)/);
    assert.equal(r.out, '', '--out must not also print to stdout');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--format pins-h writes BoardPins.h on its own', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-cli-'));
  try {
    // A fixture with pins assigned, so there is a map to write rather than an empty one.
    const fx = path.join(ROOT, 'tests', 'fixtures', 'CH32V006_TSSOP20_full.wchproj');
    const r = run(['--project', fx, '--format', 'pins-h', '--out', dir, '--quiet']);
    assert.equal(r.code, 0, r.err);
    assert.deepEqual(fs.readdirSync(dir), ['BoardPins.h'], 'the header and nothing else');
    const h = fs.readFileSync(path.join(dir, 'BoardPins.h'), 'utf8');
    assert.match(h, /#ifndef BOARD_PINS_H/);
    assert.match(h, /#define BOARD_USART1_TX_PIN\s+GPIO_Pin_\d+/);
    assert.match(h, /#define BOARD_USART1_TX_PORT\s+GPIO[A-H]/);
    // The label the fixture sets is in there too, under the name the user chose.
    assert.match(h, /BOARD_STATUS_LED_PIN/);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--format json reports conflicts, clocks and peripheral status', () => {
  const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'json', '--quiet']);
  assert.equal(r.code, 0, r.err);
  const d = JSON.parse(r.out);
  assert.equal(d.mcu, 'CH32V006');
  assert.equal(d.package, 'TSSOP20');
  assert.ok(Array.isArray(d.conflicts));
  assert.ok(Array.isArray(d.pins));
  assert.equal(typeof d.clocks.SYSCLK, 'number');
  assert.ok(Array.isArray(d.outOfSpec));
});

test('a project round-trips through the CLI and --strict fails on its conflicts', () => {
  const e = fresh('CH32V006', 'TSSOP20');
  // two peripherals that both want PA2
  for (const pid of ['ADC1', 'TKEY']) {
    const s = e.M.peripherals[pid].settings[0];
    const c = s.choices.find(x => x.signals && x.signals.length);
    if (s.type === 'checkboxes') e.toggleSetting(pid, s.name, c.name, true);
    else e.setSetting(pid, s.name, c.name);
  }
  e.setProject({ name: 'cli_strict' });
  assert.ok(e.compute().conflictList.length, 'setup: expected a conflict');

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-cli-'));
  try {
    const proj = path.join(dir, 'cli_strict.wchproj');
    fs.writeFileSync(proj, e.projectSerialize(), 'utf8');

    const loose = run(['--project', proj, '--format', 'json', '--quiet']);
    assert.equal(loose.code, 0, 'without --strict a conflicted project still generates');
    const d = JSON.parse(loose.out);
    assert.equal(d.project, 'cli_strict', 'the project name should survive the round trip');
    assert.equal(d.package, 'TSSOP20');
    assert.ok(d.conflicts.length, 'the CLI should see the same conflict the engine does');

    const strict = run(['--project', proj, '--format', 'json', '--quiet', '--strict']);
    assert.equal(strict.code, 2, '--strict must exit 2 on a dirty configuration');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--strict is happy with a clean configuration', () => {
  const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'pins-csv', '--quiet', '--strict']);
  assert.equal(r.code, 0, 'a default configuration has nothing to complain about:\n' + r.err);
});

test('bad usage explains itself and exits 1', () => {
  const unknown = run(['NOT-A-PART', '--quiet']);
  assert.equal(unknown.code, 1);
  assert.match(unknown.err, /unknown MCU "NOT-A-PART"/);
  assert.match(unknown.err, /CH32V006/, 'it should say what is available');

  const badPkg = run(['CH32V006', '--package', 'NOPE', '--quiet']);
  assert.equal(badPkg.code, 1);
  assert.match(badPkg.err, /not a package of CH32V006/);

  const badFormat = run(['CH32V006', '--format', 'pdf']);
  assert.equal(badFormat.code, 1);
  assert.match(badFormat.err, /unknown format/);

  const noValue = run(['CH32V006', '--package']);
  assert.equal(noValue.code, 1);
  assert.match(noValue.err, /--package needs/);
});

// --pio, AGENT-4's board request 2026-09-11T13:50Z: the firmware README should not
// have to tell people to `mv` the header after generating.
function pioProject() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-pio-'));
  fs.writeFileSync(path.join(dir, 'platformio.ini'), '[env:test]\nplatform = ch32v\n', 'utf8');
  return dir;
}
const gen = (dir, ...rest) => path.join(dir, 'lib', 'wchcube_generated', ...rest);

test('--pio puts the header in include/ and the source in src/', () => {
  const dir = pioProject();
  try {
    const r = run(['CH32V006', '--package', 'TSSOP20', '--pio', dir, '--quiet']);
    assert.equal(r.code, 0, r.err);
    assert.ok(fs.existsSync(gen(dir, 'include', 'wchcube_init.h')), 'header in include/');
    assert.ok(fs.existsSync(gen(dir, 'src', 'wchcube_init.c')), 'source in src/');
    assert.equal(fs.existsSync(gen(dir, 'src', 'wchcube_init.h')), false, 'and NOT in src/ as well');
    assert.equal(r.out, '', '--pio must not also print to stdout');

    // byte-identical to --out, so the two destinations cannot drift
    const flat = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-flat-'));
    try {
      run(['CH32V006', '--package', 'TSSOP20', '--format', 'c', '--out', flat, '--quiet']);
      for (const [f, sub] of [['wchcube_init.h', 'include'], ['wchcube_init.c', 'src']]) {
        assert.equal(fs.readFileSync(gen(dir, sub, f), 'utf8'), fs.readFileSync(path.join(flat, f), 'utf8'), f);
      }
    } finally { fs.rmSync(flat, { recursive: true, force: true }); }
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--pio implies --format c, and --format still wins', () => {
  const dir = pioProject();
  try {
    run(['CH32V006', '--package', 'TSSOP20', '--pio', dir, '--quiet']);
    assert.deepEqual(fs.readdirSync(gen(dir)).sort(), ['include', 'src'], 'no pin table by default');

    run(['CH32V006', '--package', 'TSSOP20', '--pio', dir, '--format', 'c,pins-md', '--quiet']);
    assert.ok(fs.readdirSync(gen(dir)).some(n => n.endsWith('_pinout.md')),
      'a non-C file goes to the component root, where neither includeDir nor srcDir picks it up');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--pio refuses a directory that is not a PlatformIO project, and writes nothing', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-nopio-'));
  try {
    const r = run(['CH32V006', '--package', 'TSSOP20', '--pio', dir, '--quiet']);
    assert.equal(r.code, 1);
    assert.match(r.err, /is not a PlatformIO project \(no platformio\.ini\)/);
    assert.match(r.err, /Nothing was written/);
    assert.deepEqual(fs.readdirSync(dir), [], 'and it really wrote nothing');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--out and --pio together is a usage error, not a guess', () => {
  const dir = pioProject();
  try {
    const r = run(['CH32V006', '--pio', dir, '--out', dir, '--quiet']);
    assert.equal(r.code, 1);
    assert.match(r.err, /two destinations/);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

// --strict on the generator's own complaints, so CI can tell "generated" from
// "generated an explanation of what is missing".
// A part that states nothing the generator needs: CH32V006 with its codegen block
// removed. Written to a temp file and passed by path so these tests do not depend on
// what any bundled part happens to contain this week.
const NO_CODEGEN_YAML = [
  'mcu:',
  '  name: CH32V006-NOCODEGEN-CLI',
  '  inherits: CH32V006',
  '  fixture: true',
  '  remove: [codegen, gpio]',
  '',
].join('\n');

function withNoCodegenFile(fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-nocg-'));
  const yaml = path.join(dir, 'nocodegen.yaml');
  fs.writeFileSync(yaml, NO_CODEGEN_YAML, 'utf8');
  try { return fn(yaml, dir); } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

test('--strict exits 2 when the generated C carries a TODO', () => {
  withNoCodegenFile((yaml, dir) => {
    const r = run([yaml, '--format', 'c', '--strict', '--out', path.join(dir, 'gen')]);
    assert.equal(r.code, 2, 'this part has no codegen: block, so codegen emits TODOs');
    assert.match(r.err, /the generated C is a complaint, not code/);
    assert.match(r.err, /TODO/);
  });
});

test('--strict says nothing about codegen when no C was generated', () => {
  withNoCodegenFile(yaml => {
    const r = run([yaml, '--format', 'pins-csv', '--strict', '--quiet']);
    assert.equal(r.code, 0, 'a complaint is about the C; it must not fail a pin table');
  });
});

// Round-3 DONE line: "Generated C for CH32V006 has zero TODO sections and zero #error
// for a fully configured part." It is not there yet, and this test says exactly what is
// left rather than being relaxed to pass. What remains is ONE missing data block - the
// SDK function that applies each *_InitTypeDef - so every complaint must name one of its
// keys. Anything else fails here, and when AGENT-1 lands the key the list empties and
// the assertion below starts holding on its own.
const WAITING_ON = /codegen\.(init_structs|periph_handle|nvic)\b/;

test('a fully assigned CH32V006 generates C with no complaint of its own', () => {
  const e = fresh('CH32V006', 'TSSOP20');
  e.setSetting('USART1', 'Mode', 'Asynchronous');
  e.compute();
  const complaints = eng.cComplaints(eng.cFiles());
  const say = list => list.map(c => `${c.kind} ${c.file}:${c.line} ${c.text}`).join('\n');
  assert.deepEqual(complaints.filter(c => c.kind === 'error'), [], 'no #error:\n' + say(complaints));
  const unexpected = complaints.filter(c => !WAITING_ON.test(c.text));
  assert.deepEqual(unexpected, [], 'complaints not waiting on codegen.init_structs:\n' + say(unexpected));
  assert.ok(e.cSource().includes('GPIO_Init(GPIO'), 'setup: pins really were assigned');
});

test('the clock and GPIO halves are complete on their own', () => {
  const e = fresh('CH32V006', 'TSSOP20');
  e.assignSignal('PC0', { gpio: 'GPIO_Output' });
  e.compute();
  const c = e.cSource();
  const upto = c.slice(0, c.indexOf('void WCHCube_Periph_Init'));
  assert.equal(/TODO|#error/.test(upto), false, 'clocks and GPIO generate with nothing missing:\n' + upto);
});

test('cComplaints reports the line and the kind of each one', () => {
  const e = fresh();
  e.registerMcuFile(NO_CODEGEN_YAML);
  e.loadMcu('CH32V006-NOCODEGEN-CLI');
  e.compute();
  const c = eng.cComplaints(eng.cFiles());
  assert.ok(c.length, 'a part with no codegen: block always has something to say');
  assert.ok(c.every(x => x.file === 'wchcube_init.c' && x.line > 0 && x.text));
  assert.ok(c.every(x => x.kind === 'todo' || x.kind === 'error'));
  // and the line number really points at the complaint
  const lines = e.cSource().split(/\r?\n/);
  for (const x of c) assert.match(lines[x.line - 1], x.kind === 'error' ? /#error/ : /TODO:/);
});

test('--help prints usage and exits 0', () => {
  const r = run(['--help']);
  assert.equal(r.code, 0);
  assert.match(r.out, /--project/);
  assert.match(r.out, /--strict/);
  assert.match(r.out, /--pio/);
});

// --option, so the compile gate can build one fixture both ways rather than keeping two
// that can drift apart (AGENT-4, board 17:09Z).
test('--option list prints what this build honours, and nothing it does not', () => {
  const r = run(['--option', 'list']);
  assert.equal(r.code, 0, r.err);
  // the help lines are indented; the option lines are not
  const keys = r.out.split(/\r?\n/)
    .filter(l => l && !/^\s/.test(l))
    .map(l => l.split('=')[0]);
  assert.deepEqual(keys, eng.generatorOptions().map(o => o.key),
    'the same list the UI renders - one source, so the two cannot disagree');
  assert.match(r.out, /split_peripherals=false/, 'with its default');
});

test('--option overrides what the project saved, so one fixture builds both ways', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-opt-'));
  try {
    const proj = path.join(ROOT, 'tests', 'fixtures', 'CH32V006_TSSOP20_full.wchproj');
    const one = run(['--project', proj, '--format', 'c', '--out', path.join(dir, 'one'), '--quiet']);
    assert.equal(one.code, 0, one.err);
    assert.deepEqual(fs.readdirSync(path.join(dir, 'one')).sort(), ['wchcube_init.c', 'wchcube_init.h']);

    const many = run(['--project', proj, '--option', 'split_peripherals=true',
      '--format', 'c', '--out', path.join(dir, 'many'), '--quiet']);
    assert.equal(many.code, 0, many.err);
    const files = fs.readdirSync(path.join(dir, 'many'));
    assert.ok(files.length > 2, 'the same project, split: ' + files.join(', '));
    assert.ok(files.includes('wchcube_usart1.c'));
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

// --diff, §7 APP P1: a readable diff between two .wchproj files. Both are loaded for
// real (projectApply()/compute()) so the CLI's labels can never disagree with the app's.
test('--diff prints unchanged everywhere for identical files, and the changed sections for different ones', () => {
  const fx = p => path.join(ROOT, 'tests', 'fixtures', p);
  const same = run(['--diff', fx('CH32V006_TSSOP20_full.wchproj'), fx('CH32V006_TSSOP20_full.wchproj')]);
  assert.equal(same.code, 0, same.err);
  assert.match(same.out, /MCU: CH32V006 \(unchanged\)/);
  assert.match(same.out, /Pins: unchanged\./);
  assert.match(same.out, /Settings: unchanged\./);
  assert.match(same.out, /Params: unchanged\./);
  assert.match(same.out, /Clock: unchanged\./);
  assert.equal(/NOTE:/.test(same.out), false);

  const cross = run(['--diff', fx('CH32V006_QFN32_full.wchproj'), fx('CH32V003_TSSOP20_full.wchproj')]);
  assert.equal(cross.code, 0, cross.err);
  assert.match(cross.out, /MCU: CH32V006 -> CH32V003/);
  assert.match(cross.out, /NOTE: the two projects are for different parts/);
  assert.match(cross.out, /Pins \(\d+ changed\):/);
});

test('--diff refuses a project naming an MCU that is not loaded, and says which of the two files', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-diff-'));
  try {
    const good = path.join(ROOT, 'tests', 'fixtures', 'CH32V006_TSSOP20_full.wchproj');
    const bogus = path.join(dir, 'bogus.wchproj');
    fs.writeFileSync(bogus, fs.readFileSync(good, 'utf8').replace('mcu: CH32V006', 'mcu: NOSUCHPART9000'), 'utf8');

    const r = run(['--diff', bogus, good]);
    assert.equal(r.code, 1);
    assert.match(r.err, /A: "NOSUCHPART9000" is not loaded/);

    const r2 = run(['--diff', good, bogus]);
    assert.equal(r2.code, 1);
    assert.match(r2.err, /B: "NOSUCHPART9000" is not loaded/);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--diff refuses a missing file by name, before trying to parse anything', () => {
  const good = path.join(ROOT, 'tests', 'fixtures', 'CH32V006_TSSOP20_full.wchproj');
  const r = run(['--diff', good, path.join(ROOT, 'tests', 'fixtures', 'does-not-exist.wchproj')]);
  assert.equal(r.code, 1);
  assert.match(r.err, /no such project file/);

  const r2 = run(['--diff', path.join(ROOT, 'tests', 'fixtures', 'does-not-exist.wchproj'), good]);
  assert.equal(r2.code, 1);
  assert.match(r2.err, /no such project file/);
});

test('--diff needs two paths', () => {
  const r = run(['--diff', path.join(ROOT, 'tests', 'fixtures', 'CH32V006_TSSOP20_full.wchproj')]);
  assert.equal(r.code, 1);
  assert.match(r.err, /--diff needs a second \.wchproj path/);
});

test('--option refuses a key this build does not have, and says which it does', () => {
  const bad = run(['CH32V006', '--option', 'nope=1', '--quiet']);
  assert.equal(bad.code, 1);
  assert.match(bad.err, /No generator option "nope"/);
  assert.match(bad.err, /split_peripherals/, 'it should say what is available');

  const noEq = run(['CH32V006', '--option', 'split_peripherals', '--quiet']);
  assert.equal(noEq.code, 1);
  assert.match(noEq.err, /wants key=value/);

  const badValue = run(['CH32V006', '--option', 'reports=perhaps', '--quiet']);
  assert.equal(badValue.code, 1);
  assert.match(badValue.err, /expected true or false/);
});
