// tools/wchcube_cli.js — the engine without a browser.
//
// CI diffs this output, so the contract is: the CLI must produce the same bytes the
// GENERATE CODE button produces, and its exit codes must mean something. If the two
// ever drift, a generated-output diff in CI stops being evidence about the app.
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { test, assert, fresh, eng, ROOT } from './_harness.js';

const CLI = path.join(ROOT, 'tools', 'wchcube_cli.js');

function run(args, opts) {
  const r = spawnSync(process.execPath, [CLI, ...args], {
    cwd: ROOT, encoding: 'utf8', timeout: 60000, ...(opts || {}),
  });
  if (r.error) throw r.error;
  return { code: r.status, out: r.stdout, err: r.stderr };
}

test('--list names every MCU file with its packages', () => {
  const r = run(['--list']);
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /CH32V006/);
  assert.match(r.out, /TSSOP20/);
  // a part that only exists through mcu.inherits must show its inherited packages
  assert.match(r.out, /CH32V005[\s\S]*packages\s+.*TSSOP20/);
});

test('the pin table is byte-identical to the one the app exports', () => {
  const e = fresh('CH32V006', 'TSSOP20');
  const inProcess = e.pinTableMarkdown();
  const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'pins-md', '--quiet']);
  assert.equal(r.code, 0, r.err);
  assert.equal(r.out, inProcess.endsWith('\n') ? inProcess : inProcess + '\n',
    'CLI output drifted from pinTableMarkdown() — CI diffs would stop meaning anything');
});

test('the CSV and the clock summary come out of the same functions', () => {
  const e = fresh('CH32V006', 'QFN32');
  const csv = run(['CH32V006', '--package', 'QFN32', '--format', 'pins-csv', '--quiet']);
  const clk = run(['CH32V006', '--package', 'QFN32', '--format', 'clocks-md', '--quiet']);
  assert.equal(csv.code, 0, csv.err);
  assert.equal(clk.code, 0, clk.err);
  assert.equal(csv.out.trimEnd(), e.pinTableCsv().trimEnd());
  assert.equal(clk.out.trimEnd(), e.clockSummaryMarkdown().trimEnd());
});

test('--format c writes the two init files, --out puts them on disk', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-cli-'));
  try {
    const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'c', '--out', dir, '--quiet']);
    assert.equal(r.code, 0, r.err);
    const written = fs.readdirSync(dir).sort();
    assert.deepEqual(written, ['wchcube_init.c', 'wchcube_init.h']);
    const c = fs.readFileSync(path.join(dir, 'wchcube_init.c'), 'utf8');
    assert.match(c, /generated by WCHCube/);
    assert.match(c, /void WCHCube_GPIO_Init\(void\)/);
    assert.equal(r.out, '', '--out must not also print to stdout');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--format json reports conflicts, clocks and peripheral status', () => {
  const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'json', '--quiet']);
  assert.equal(r.code, 0, r.err);
  const d = JSON.parse(r.out);
  assert.equal(d.mcu, 'CH32V006');
  assert.equal(d.package, 'TSSOP20');
  assert.ok(Array.isArray(d.conflicts));
  assert.ok(Array.isArray(d.pins));
  assert.equal(typeof d.clocks.SYSCLK, 'number');
  assert.ok(Array.isArray(d.outOfSpec));
});

test('a project round-trips through the CLI and --strict fails on its conflicts', () => {
  const e = fresh('CH32V006', 'TSSOP20');
  // two peripherals that both want PA2
  for (const pid of ['ADC1', 'TKEY']) {
    const s = e.M.peripherals[pid].settings[0];
    const c = s.choices.find(x => x.signals && x.signals.length);
    if (s.type === 'checkboxes') e.toggleSetting(pid, s.name, c.name, true);
    else e.setSetting(pid, s.name, c.name);
  }
  e.setProject({ name: 'cli_strict' });
  assert.ok(e.compute().conflictList.length, 'setup: expected a conflict');

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wchcube-cli-'));
  try {
    const proj = path.join(dir, 'cli_strict.wchproj');
    fs.writeFileSync(proj, e.projectSerialize(), 'utf8');

    const loose = run(['--project', proj, '--format', 'json', '--quiet']);
    assert.equal(loose.code, 0, 'without --strict a conflicted project still generates');
    const d = JSON.parse(loose.out);
    assert.equal(d.project, 'cli_strict', 'the project name should survive the round trip');
    assert.equal(d.package, 'TSSOP20');
    assert.ok(d.conflicts.length, 'the CLI should see the same conflict the engine does');

    const strict = run(['--project', proj, '--format', 'json', '--quiet', '--strict']);
    assert.equal(strict.code, 2, '--strict must exit 2 on a dirty configuration');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

test('--strict is happy with a clean configuration', () => {
  const r = run(['CH32V006', '--package', 'TSSOP20', '--format', 'pins-csv', '--quiet', '--strict']);
  assert.equal(r.code, 0, 'a default configuration has nothing to complain about:\n' + r.err);
});

test('bad usage explains itself and exits 1', () => {
  const unknown = run(['NOT-A-PART', '--quiet']);
  assert.equal(unknown.code, 1);
  assert.match(unknown.err, /unknown MCU "NOT-A-PART"/);
  assert.match(unknown.err, /CH32V006/, 'it should say what is available');

  const badPkg = run(['CH32V006', '--package', 'NOPE', '--quiet']);
  assert.equal(badPkg.code, 1);
  assert.match(badPkg.err, /not a package of CH32V006/);

  const badFormat = run(['CH32V006', '--format', 'pdf']);
  assert.equal(badFormat.code, 1);
  assert.match(badFormat.err, /unknown format/);

  const noValue = run(['CH32V006', '--package']);
  assert.equal(noValue.code, 1);
  assert.match(noValue.err, /--package needs/);
});

test('--help prints usage and exits 0', () => {
  const r = run(['--help']);
  assert.equal(r.code, 0);
  assert.match(r.out, /--project/);
  assert.match(r.out, /--strict/);
});
