// =============================================================================
//  app/tests/pinmap.test.js — BoardPins.h, the pin map on its own.
//
//  What it is for: somebody who already has a project drops ONE file into it and can
//  write `BOARD_USART1_TX` instead of `GPIO_Pin_9`. So the two things that have to hold
//  are that every macro is a REAL answer (the same pin and AF the generated C uses) and
//  that the file can be produced without the machinery a full project needs - no part
//  number, no board, no PlatformIO at all.
//
//  Every macro is checked against the engine's own accessors rather than against a
//  hardcoded expectation, because a test that repeats the generator's arithmetic is the
//  same class of bug as data that repeats it.
// =============================================================================
import { test, assert, fresh, mcuNames } from './_harness.js';

/** A part with an AF-muxed routing (H417) and one with a `remaps:` index (V006). */
const AF_PART = 'CH32H417';
const REMAP_PART = 'CH32V006';

const wired = (mcu = REMAP_PART, pkg) => {
  const e = fresh(mcu, pkg);
  e.setSetting('USART1', 'Mode', 'Asynchronous');
  e.compute();
  return e;
};

/** The `#define` lines of a header, as `{ name, value }`. */
function defines(text) {
  const out = [];
  for (const m of text.matchAll(/^#define\s+(\S+)\s+(.+?)\s*$/gm)) out.push({ name: m[1], value: m[2] });
  return out;
}

test('the header is self-contained: guard, SDK include, and balanced defines', () => {
  const e = wired();
  const t = e.pinMapHeader();
  assert.match(t, /^\/\* =+/, 'it opens with the generated-file banner');
  assert.ok(t.includes('Generated by WCHCube'), 'and says it is generated');
  assert.ok(t.includes(`Part    : ${e.M.mcu.name}`), 'naming the part');
  assert.match(t, /#ifndef BOARD_PINS_H\n#define BOARD_PINS_H/, 'with an include guard');
  assert.ok(t.includes('#endif /* BOARD_PINS_H */'), 'and closes it');
  // The macros use GPIOA / GPIO_Pin_9 / GPIO_AF7, so the SDK header has to be there or
  // the file does not compile in the project it was dropped into.
  const inc = /#include "([^"]+)"/.exec(t);
  assert.ok(inc, 'it includes a header');
  assert.equal(inc[1], e.M.codegen.header, 'the SDK header the MCU file names, not a guess');
  // Nothing that would fail a build of the user's own project.
  assert.deepEqual(t.split('\n').filter(l => /\bTODO\b|#error/.test(l)), []);
});

test('every macro is the pin and AF the generated C actually uses', () => {
  const e = wired(AF_PART, 'QFN128');
  const map = e.pinMap();
  assert.ok(map.entries.length, 'setup: something is assigned');
  const d = defines(e.pinMapHeader());
  const by = name => (d.find(x => x.name === name) || {}).value;

  for (const v of map.entries) {
    // `GPIOx` / `GPIO_Pin_n` are the SPL's own spelling of the pad, derived from the pin
    // name by the same PARSE the rest of the app does - not restated here.
    const m = /^P([A-H])(\d+)$/.exec(v.pin);
    assert.ok(m, `${v.macro}: ${v.pin} is a port pin`);
    assert.equal(by(`${v.macro}_PORT`), `GPIO${m[1]}`, `${v.macro}_PORT`);
    assert.equal(by(`${v.macro}_PIN`), `GPIO_Pin_${m[2]}`, `${v.macro}_PIN`);
    // The AF, where the data states one - compared against the engine's own answer.
    if (v.af !== null && v.af !== undefined) {
      assert.equal(by(`${v.macro}_AF`), `GPIO_AF${v.af}`, `${v.macro}_AF`);
    } else {
      assert.equal(by(`${v.macro}_AF`), undefined, `${v.macro}: no AF macro when the data states none`);
    }
  }
  // And the claim itself: an AF-muxed pad really does carry its code.
  const tx = map.entries.find(v => v.name === 'USART1_TX');
  assert.ok(tx, 'setup: USART1_TX is mapped');
  assert.equal(tx.af, e.signalAf('USART1', 'TX', tx.pin), 'the AF is signalAf()s answer');
  assert.equal(by('BOARD_USART1_TX_AF'), `GPIO_AF${tx.af}`);
});

test('a user label becomes its own macro, sanitised to an identifier', () => {
  const e = wired();
  e.setGpioField('PA1', 'mode', 'Output Push Pull');
  e.setGpioField('PA1', 'label', 'Status Led!');
  e.compute();
  const d = defines(e.pinMapHeader());
  const by = n => (d.find(x => x.name === n) || {}).value;
  assert.equal(by('BOARD_STATUS_LED_PORT'), 'GPIOA', 'the spaces and the bang are folded to underscores');
  assert.equal(by('BOARD_STATUS_LED_PIN'), 'GPIO_Pin_1');
  // a label is not a peripheral signal, so it has no AF and must not invent one
  assert.equal(by('BOARD_STATUS_LED_AF'), undefined);
});

test('a name collision is reported, never emitted twice', () => {
  // Two labels that fold to the same identifier is a `#define` that silently keeps the
  // last one - a wrong build nobody sees. It has to be caught, not shipped.
  const e = wired();
  e.setGpioField('PA1', 'mode', 'Output Push Pull');
  e.setGpioField('PA1', 'label', 'LED A');
  e.setGpioField('PA2', 'mode', 'Output Push Pull');
  e.setGpioField('PA2', 'label', 'LED_A');
  e.compute();
  const map = e.pinMap();
  assert.equal(map.collisions.length, 1, `expected one collision: ${JSON.stringify(map.collisions)}`);
  assert.match(map.collisions[0], /BOARD_LED_A/, 'and it names the macro');
  // NEITHER is emitted, and that is the point: keeping the first would give the user a
  // board where BOARD_LED_A is a pad they did not mean, and it would compile.
  assert.ok(!map.entries.some(v => v.macro === 'BOARD_LED_A'), 'neither is emitted');
  assert.match(map.text, /COLLISION \(not emitted\)/, 'the file says so too');
  const d = defines(map.text);
  assert.equal(d.filter(x => x.name === 'BOARD_LED_A_PIN').length, 0, 'so no define exists at all');
  // the other macros are unaffected - one clash must not empty the file
  assert.ok(map.entries.length >= 1, 'the rest of the map survives a clash');
});

test('a part with nothing assigned says so rather than shipping an empty file', () => {
  const e = fresh(REMAP_PART);
  e.compute();
  const t = e.pinMapHeader();
  // SYS's debug pair is on by default on this part, so "nothing" means no `_PORT`
  // macro for a pad the user chose - the wording only appears when the map is empty.
  const map = e.pinMap();
  if (!map.entries.length) {
    assert.match(t, /NO PIN IS ASSIGNED/, 'an empty map explains itself');
  } else {
    assert.ok(t.includes('#define BOARD_'), 'or there is something to map');
  }
  assert.ok(t.includes('#ifndef BOARD_PINS_H'), 'and the file is still valid either way');
});

test('pin_map_only produces the header alone, and needs no part number', () => {
  // QSOP24 and QFN12 of this part have NO PlatformIO board, so the full project cannot be
  // generated at all. That is exactly the user this option is for: they have their own
  // project and only want the map. Asserted on a package that really refuses, not on one
  // that happens to work.
  const e = fresh(REMAP_PART, 'QSOP24');
  e.setSetting('USART1', 'Mode', 'Asynchronous');
  e.compute();
  assert.ok(e.pioTarget().missing, 'setup: this package has no board, so a project cannot be generated');
  assert.throws(() => e.projectFiles(), /Cannot generate a PlatformIO project/);

  e.setGeneratorOption('pin_map_only', true);
  // reports are a separate option and are on by default, so turn them off to assert the
  // scope precisely - one file, and it is the header.
  e.setGeneratorOption('reports', false);
  const files = e.projectFiles();
  assert.deepEqual(files.map(f => f.path), ['BoardPins.h'], 'the header, and nothing else');
  assert.ok(files[0].text.includes('BOARD_USART1_TX_PIN'), 'carrying the map');
  e.setGeneratorOption('reports', true);
  assert.deepEqual(e.projectFiles().map(f => f.path),
    ['BoardPins.h', 'CH32V006_QSOP24_pinout.md', 'CH32V006_QSOP24_pinout.csv', 'CH32V006_QSOP24_clocks.md'],
    'and the reports are still available when wanted');
  // the same scope through generateAll(), which is what the CLI uses
  assert.ok(e.generateAll().some(f => f.name === 'BoardPins.h'));
  assert.equal(e.generateAll().some(f => /wchcube_init/.test(f.name)), false,
    'and no init files: their own project has its own');
});

test('the full project gets BoardPins.h beside the init header, or not at all', () => {
  const e = wired(REMAP_PART, 'TSSOP20');
  const full = e.projectFiles().map(f => f.path);
  assert.ok(full.includes('lib/wchcube_generated/include/BoardPins.h'),
    'in the component include dir, so #include "BoardPins.h" resolves the same way');
  assert.ok(full.includes('lib/wchcube_generated/include/wchcube_init.h'), 'beside the init header');
  e.setGeneratorOption('pin_map', false);
  assert.equal(e.projectFiles().some(f => /BoardPins/.test(f.path)), false, 'the option removes it');
  e.setGeneratorOption('pin_map', true);
  assert.ok(e.generateAll().some(f => f.name === 'BoardPins.h'), 'and generateAll honours it too');
});

test('every shipped part produces a header that parses as C preprocessor output', () => {
  // A sweep, because the file is generated for whichever part is loaded and the failure
  // mode is one part whose pin names or labels break the macro spelling.
  const bad = [];
  for (const name of mcuNames().filter(n => !/DUMMY/i.test(n))) {
    const e = fresh(name);
    // assign the first peripheral that has a Mode setting, so there is a real signal
    const pid = Object.keys(e.M.peripherals).find(p => (e.M.peripherals[p].settings || []).some(s => s.name === 'Mode'));
    if (pid) { try { e.setSetting(pid, 'Mode', e.M.peripherals[pid].settings.find(s => s.name === 'Mode').choices[1].name); } catch { /* leave default */ } }
    e.compute();
    const map = e.pinMap();
    if (map.collisions.length) bad.push(`${name}: ${map.collisions.join('; ')}`);
    for (const v of map.entries) {
      // A macro name must survive the C preprocessor: letters, digits, underscore.
      if (!/^[A-Z_][A-Z0-9_]*$/.test(v.macro)) bad.push(`${name}: "${v.macro}" is not an identifier`);
      if (!/^BOARD_/.test(v.macro)) bad.push(`${name}: "${v.macro}" is not namespaced`);
      if (!/^P[A-H]\d+$/.test(v.pin)) bad.push(`${name}: ${v.macro} is on ${v.pin}, not a port pin`);
    }
  }
  assert.deepEqual(bad.slice(0, 10), []);
});
